spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
        git:
          uri: "https://github.com/cesarpa/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
    key: "s3cr3tK3yF0r3azybyt3s"

server:
  port: 8071

